---
- name: Provision ec2 instances for Opneshift Cluster
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev-environment.yml
    - vars/aws-creds.yml

  tasks:

  - name: Launch Master Node
    ec2: 
      region: us-east-2
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: Ansible
      image: ami-14c5486b
      instance_type: m1.small
      group: "CentOS 7 -x86_64-- with Updates HVM-1805_01-AutogenByAWSMP-"
      wait: true
      instance_tags:
          Name: Master_Node
      count_tag:
        Name: worker_node
      exact_count: "{{num_masters}}"
      
  - name: Launch Infra Node
    ec2: 
      region: us-east-2
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: Ansible
      image: ami-14c5486b
      instance_type: m1.small
      group: "CentOS 7 -x86_64-- with Updates HVM-1805_01-AutogenByAWSMP-"
      wait: true
      instance_tags:
          Name: Infra_Node
      count_tag:
        Name: worker_node
      exact_count: "{{num_infras}}"
      
  - name: Launch Worker Nodes
    ec2: 
      region: us-east-2
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: Ansible
      image: ami-14c5486b
      instance_type: m1.small
      group: "CentOS 7 -x86_64-- with Updates HVM-1805_01-AutogenByAWSMP-"
      wait: true
      instance_tags:
          Name: Worker_Node
      count_tag:
        Name: worker_node
      exact_count: "{{num_workers}}"
