---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
   - vars/aws-creds.yml
  tasks:
  - name: Instace deletion
    ec2:
     region: us-east-1
     ec2_access_key: "{{ ec2_access_key }}"
     ec2_secret_key: "{{ ec2_secret_key }}"
     state: absent
     instance_ids: "{{ instance_id }}"
