---
- hosts: localhost
  gather_facts: false
 
  tasks:
  
  - name: git download
    git:
      repo: "https://github.com/Michaelsliem/azure-Openshift-deploy.git"
      key_file: /var/lib/awx/.ssh/id_rsa
      accept_hostkey: True
      dest: /var/lib/awx/download
      force: yes
      version: master
