---
- hosts: localhost
  gather_facts: yes
  become_user: root
  become_method: sudo
  
  tasks:
  - name: restart service
    service:
        name: network
        state: restarted
        enabled: yes  
