---
- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev-environment.yml
    - vars/aws-creds.yml

  tasks:

  - name: Launch instances
    ec2: 
      region: us-east-1
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: Ansible
      image: ami-14c5486b
      instance_type: m1.small
      wait: true
