---
# set these parameters to control the region, keypair, and AMI that are launched
ec2_region: us-west-1
instances_keypair: Ansible 
image_id: ami-9887c6e7


  
# Instances to launch be launched.
# If you re-run the playbook after modifying exact_count,
# instances will be terminated if the actual count > exact_count,
# or new instances will be launched if actual count < exact_count.

ec2_instances:
  - instance_type: m1.small
    image: "{{ image_id }}"
    keypair: "{{instances_keypair}}"
    instance_tags: 
        Name: web
    exact_count: 1 
    count_tag: 
        Name: web
